[project]
name = "tccmcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.0",
    "python-whois>=0.9.5",
    "scapy>=2.6.1",
]
